import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/session-provider";

const work_sans_init = Work_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Randomly",
  description: "Generated by create next app",
   icons: {
  icon: [
    { url: "/logo.jpg", type: "image/jpg" },
  ],
}

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${work_sans_init.className} antialiased`}
      >
    <Providers>
        
        {children}
        </Providers>
      </body>
    </html>
  );
}
